name: react-resume-dev

services:
  server:
    image: node:lts-slim
    ports:
      - 5173:${REACTRESUME_PORT:-5173}
    volumes:
      - .:/usr/share/app
    working_dir: /usr/share/app
    tty: true
    entrypoint:
      - npm
      - run
      - dev

  components:
    image: node:lts-slim
    volumes:
      - .:/usr/share/app
    working_dir: /usr/share/app/packages/components
    tty: true
    entrypoint:
      - npm
      - run
      - dev

  templates:
    image: node:lts-slim
    volumes:
      - .:/usr/share/app
    working_dir: /usr/share/app/packages/template
    tty: true
    entrypoint:
      - npm
      - run
      - dev

  types:
    image: node:lts-slim
    volumes:
      - .:/usr/share/app
    working_dir: /usr/share/app/packages/types
    tty: true
    entrypoint:
      - npm
      - run
      - dev
