name: react-resume-dev

services:
  server:
    image: node:lts-slim
    ports:
      - 5173:${REACTRESUME_PORT:-5173}
    volumes:
      - .:/usr/share/app
    working_dir: /usr/share/app
    tty: true
    entrypoint:
      - npm
      - run
      - dev